name: 哔哩哔哩录播姬
version: "2.15"
slug: bililive_recorder
description: 基于BililiveRecorder录播姬的直播录制工具
url: https://github.com/mikephemera/HomeAssistant-BililiveRecorder/
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
map:
  - type: share
    read_only: false
    path: /rec
# 移除端口映射（通过Ingress访问）
ingress: true
ingress_port: 2356  # 与服务实际监听端口一致
options:
  storage_path: /share/bilirec
  username: admin   # 保留配置但不在插件中使用
  password: password
  umask: "022"
  pgid: 1000
  puid: 1000
schema:
  storage_path: str
  username: str
  password: str
  umask: "str?"
  pgid: "int?"
  puid: "int?"
image: bililive/recorder

# 环境变量
environment:
  BREC_HTTP_OPEN_ACCESS: "true"
  #BREC_HTTP_BASIC_USER: ${username} # 通过Ingress访问时不需要
  #BREC_HTTP_BASIC_PASS: ${password}

panel_icon:	mdi:television-classic