name: 哔哩录播姬
version: "2.0.0"
slug: bililive_recorder
description: 基于BililiveRecorder的直播录制工具
url: https://rec.danmuji.org/
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
map:
  - type: share
    read_only: false
    path: /rec
ports:
  "2356/tcp": 2356
ports_description:
  "2356/tcp": Web管理界面端口
options:
  storage_path: /share/bilirec
  username: admin
  password: password
  umask: "022"
  pgid: 1000
  puid: 1000
schema:
  storage_path: str
  username: str
  password: str
  umask: "str?"
  pgid: "int?"
  puid: "int?"
image: bililive/recorder